# Generated by Django 3.2.9 on 2021-11-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('street', models.CharField(max_length=64, verbose_name='Улица')),
                ('house', models.CharField(max_length=25, verbose_name='Дом')),
                ('flat', models.CharField(max_length=4, verbose_name='Квартира')),
                ('adress_sender', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45, verbose_name='Фамилия')),
                ('lname', models.CharField(max_length=45, verbose_name='Имя')),
                ('login', models.CharField(max_length=25, verbose_name='Логин')),
                ('email', models.EmailField(max_length=40)),
                ('telefon', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateTimeField()),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count_loader', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий к заказу')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='db.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45, verbose_name='Фамилия')),
                ('lname', models.CharField(max_length=45, verbose_name='Имя')),
                ('login', models.CharField(max_length=25, verbose_name='Логин')),
                ('email', models.EmailField(max_length=40)),
                ('telefon', models.CharField(max_length=12, verbose_name='Телефон')),
                ('car_number', models.CharField(max_length=12, verbose_name='Номер машины')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45, verbose_name='Фамилия')),
                ('lname', models.CharField(max_length=45, verbose_name='Имя')),
                ('login', models.CharField(max_length=25, verbose_name='Логин')),
                ('email', models.EmailField(max_length=40)),
                ('telefon', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45, verbose_name='Фамилия')),
                ('lname', models.CharField(max_length=45, verbose_name='Имя')),
                ('login', models.CharField(max_length=25, verbose_name='Логин')),
                ('email', models.EmailField(max_length=40)),
                ('telefon', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45, verbose_name='Фамилия получателя')),
                ('lname', models.CharField(max_length=45, verbose_name='Имя получателя')),
                ('telefon', models.CharField(max_length=12, verbose_name='Телефон получателя')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_Recipient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='routes_recipient', to='db.adress', verbose_name='Адрес получателя')),
                ('adress_Sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='routes_sender', to='db.adress', verbose_name='Адрес отправителя')),
            ],
        ),
        migrations.CreateModel(
            name='LoadersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='loaders', to='db.contract', verbose_name='Заказ')),
                ('loader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='loaders', to='db.loader', verbose_name='Грузчик')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='db.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='contract',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='db.manager', verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='contract',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='db.recipient', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='contract',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='db.route', verbose_name='Маршрут'),
        ),
    ]
