# Generated by Django 3.2.9 on 2021-12-10 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdressRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('street', models.CharField(max_length=64, verbose_name='Улица')),
                ('house', models.CharField(max_length=25, verbose_name='Дом')),
                ('flat', models.CharField(max_length=4, verbose_name='Квартира')),
            ],
        ),
        migrations.CreateModel(
            name='AdressSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('street', models.CharField(max_length=64, verbose_name='Улица')),
                ('house', models.CharField(max_length=25, verbose_name='Дом')),
                ('flat', models.CharField(max_length=4, verbose_name='Квартира')),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='car_number',
        ),
        migrations.AlterField(
            model_name='route',
            name='adress_Recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='routes_recipient', to='db.adressrecipient', verbose_name='Адрес получателя'),
        ),
        migrations.AlterField(
            model_name='route',
            name='adress_Sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='routes_sender', to='db.adresssender', verbose_name='Адрес отправителя'),
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
