# Generated by Django 3.2.9 on 2021-12-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.IntegerField(choices=[(0, 'client'), (1, 'manager'), (2, 'loader'), (3, 'driver')], default=0),
        ),
    ]
