# Generated by Django 3.2.9 on 2021-12-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_telefon',
            new_name='telefon',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login',
            field=models.CharField(default='guest', max_length=25, verbose_name='Логин'),
        ),
    ]
